FROM archlinux

RUN mkdir -p /go/src/app
WORKDIR /go/src/app
ENV GOPATH=/go
COPY . .

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm go git

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["app"]

RUN go get github.com/tidwall/gjson
RUN go get github.com/gorilla/mux

CMD go run *.go
