FROM archlinux

WORKDIR /go/src/app
ENV GOPATH=/go
COPY . .

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm go git

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["app"]

RUN go get github.com/tidwall/gjson
RUN go get github.com/gorilla/mux
RUN go get github.com/dgrijalva/jwt-go
RUN go get golang.org/x/crypto/bcrypt
RUN go get github.com/joho/godotenv

CMD go run *.go
